-- Partial refunds + exchanges. A paid order can now be refunded line-by-line (a chosen quantity of
-- chosen lines) any number of times, instead of only in full. Each refund is one row in
-- order_refunds — Shopify-style refund records — capturing what was returned, any exchange
-- replacement accessories that were shipped in the same order, the net cash refunded, the reason
-- and supporting documents. When every refundable unit has been returned the order still lands on
-- the terminal 'refunded' status (0035); until then payment_status becomes 'partially_refunded'.
--
-- Exchange semantics ("多退少不补"): returned value R, replacement value P, cash refunded =
-- max(0, R - P). Replacement lines are added to the order's quote as $0-to-customer accessory lines
-- (config.exchange = true) — the retailer is never charged the balance when P > R.

create table if not exists public.order_refunds (
  id                 bigint generated by default as identity primary key,
  order_id           bigint not null references public.orders(id) on delete cascade,
  -- Net cash refunded to the customer for THIS refund event = max(0, returned_value - replacement_value).
  amount             numeric(10,2) not null default 0 check (amount >= 0),
  -- Value of the returned line quantities (R) and of the exchange replacement goods (P), snapshotted.
  returned_value     numeric(10,2) not null default 0,
  replacement_value  numeric(10,2) not null default 0,
  reason             text not null,
  -- Supporting documents (image/PDF) in the private payment-proofs bucket — same pattern as tracking_nos.
  doc_paths          jsonb not null default '[]'::jsonb,
  -- Returned lines: [{ itemId, qty, amount }] (amount = unit price snapshot * qty).
  line_items         jsonb not null default '[]'::jsonb,
  -- Exchange replacements shipped in this order: [{ itemId, productId, qty, value, name }] (value = P part).
  replacement_items  jsonb not null default '[]'::jsonb,
  -- Whether reserved motor stock was released for the returned lines (pre-shipment only).
  restocked          boolean not null default false,
  created_at         timestamptz not null default now()
);

create index if not exists order_refunds_order_idx on public.order_refunds(order_id);

-- payment_status gains 'partially_refunded' (0035 added 'refunded'). Drop + re-add so it's re-runnable.
alter table public.orders drop constraint if exists orders_payment_status_chk;
alter table public.orders add constraint orders_payment_status_chk
  check (payment_status in ('pending','paid','failed','refunded','partially_refunded'));

-- =========================================================
-- RLS: ownership via order → quote (mirrors order_events). Reads for the owning retailer or an
-- admin; writes are admin-only (refunds are always admin-initiated).
-- =========================================================
alter table public.order_refunds enable row level security;

drop policy if exists order_refunds_select on public.order_refunds;
create policy order_refunds_select on public.order_refunds
  for select using (
    exists (
      select 1 from public.orders o
      join public.quotes q on q.id = o.quote_id
      where o.id = order_refunds.order_id
        and (q.owner_id = auth.uid() or q.owner_id is null or public.is_admin())
    )
  );

drop policy if exists order_refunds_insert on public.order_refunds;
create policy order_refunds_insert on public.order_refunds
  for insert with check (public.is_admin());

drop policy if exists order_refunds_update on public.order_refunds;
create policy order_refunds_update on public.order_refunds
  for update using (public.is_admin()) with check (public.is_admin());

drop policy if exists order_refunds_delete on public.order_refunds;
create policy order_refunds_delete on public.order_refunds
  for delete using (public.is_admin());
