-- Window-coverings ERP v1 — core schema (L1 templates / L2 merchant products / L3 commerce data).
-- Spec: docs/superpowers/specs/2026-07-24-window-coverings-erp-v1-design.md
--
-- Three layers:
--   L1 product_templates    — platform-owned, seeded from blind-bot render3d schemas
--                             (data/templates/render3d-*.json) plus commercial extension fields.
--   L2 catalog_products     — a merchant org's sellable products: a template pin + per-field
--                             policies (isOffered / allowedValues / defaults), shape-identical to
--                             blind-bot's Product3dScheme FieldPolicy for future sync.
--   L3 commerce tables      — price groups, W×H grids, surcharges, size constraints, dealer
--                             accounts + factors, freight. All org-scoped and effective-dated:
--                             these change on live-order timescales (the anchor customer keeps
--                             hand-written Log sheets for exactly this reason).
--
-- v1 runs single-org, but every org-owned table carries org_id from day 1 so multi-tenant needs
-- no backfill. Dimensions and prices deliberately live OUTSIDE the variation/policy documents,
-- mirroring blind-bot where variationsJsonV2 carries neither.

-- ============================================================
-- Orgs & dealer accounts
-- ============================================================

-- A tenant company on the platform. v1 seeds exactly one (the anchor factory); the platform
-- admin UI for switching orgs comes later.
create table if not exists public.orgs (
  id          bigint generated by default as identity primary key,
  name        text not null,
  kind        text not null default 'manufacturer' check (kind in ('manufacturer','retailer')),
  settings    jsonb not null default '{}'::jsonb,
  created_at  timestamptz not null default now()
);

-- A dealer COMPANY buying from an org (the anchor factory's ~dealers). Multiple auth users
-- (profiles) can belong to one dealer account; account factors and QuickBooks refs hang off the
-- company, not the individual login. Fixes the existing gap where profiles.company is free text.
create table if not exists public.dealer_accounts (
  id          bigint generated by default as identity primary key,
  org_id      bigint not null references public.orgs(id),
  name        text not null,
  -- {contactName, phone, email, addresses: [...]} — noise-free camelCase, omit empties.
  contact     jsonb not null default '{}'::jsonb,
  qb_ref      text,
  created_at  timestamptz not null default now()
);
create index if not exists dealer_accounts_org_idx on public.dealer_accounts(org_id);

-- Link auth users to an org (staff) and optionally a dealer account (dealer users).
alter table public.profiles add column if not exists org_id bigint references public.orgs(id);
alter table public.profiles add column if not exists dealer_account_id bigint references public.dealer_accounts(id);

-- ============================================================
-- L1 — product templates
-- ============================================================

-- One template per product line (blind-bot global_subcategories.key: 'roller_shade',
-- 'banded_shade', 'plantation_shutter', ...). org_id NULL = platform-global (the normal case);
-- an org-specific template row can shadow the global one later if ever needed.
--
-- fields:     ordered TemplateField[] — render3d VariationDescriptor superset. Visual axes come
--             verbatim from the render3d schema export; commercial extension fields (motor chain,
--             chargers, side channels, ...) use the same shape with EnumSpec canonical-token keys
--             and origin='commercial'.
-- sections:   [{key,label,visibleWhen?}] configurator card grouping.
-- dimensions: [{key,label,unit:'in',min,max,step,display:'fraction_8th'}] — line-item dimension
--             fields (width/height), NOT variation fields.
-- rules:      render3d WriteRule subset for cross-field cascades (applied client-side in the
--             configurator; server re-validates the final config).
-- source:     {package:'@blindbot/render3d', engineVersion, schemaVersion, exportedAt} when
--             derived from blind-bot — the pin that makes future re-sync diffable.
create table if not exists public.product_templates (
  id           bigint generated by default as identity primary key,
  org_id       bigint references public.orgs(id),          -- NULL = platform-global
  line_key     text not null,
  label        text not null,
  revision     int not null default 1,
  status       text not null default 'draft' check (status in ('draft','published','archived')),
  source       jsonb,
  fields       jsonb not null default '[]'::jsonb,
  sections     jsonb not null default '[]'::jsonb,
  dimensions   jsonb not null default '[]'::jsonb,
  rules        jsonb not null default '[]'::jsonb,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  unique (line_key, revision)
);

-- ============================================================
-- L2 — merchant catalog products
-- ============================================================

-- A sellable product of an org, e.g. "Sunnex Poly Shutter". Pins the template revision it was
-- authored against (orders additionally snapshot everything they need — snapshot discipline).
--
-- field_policies: { [fieldKey]: FieldPolicy } — discriminated on controlKind, each with
-- isOffered plus kind-specific narrowing (allowedValues / range / allowedColors /
-- allowedPatterns / defaultValue, labelOverride, optionLabels). Structurally identical to
-- blind-bot variations_3d_json_v1 fields so a future blind-bot<->quoting product sync is a
-- field-key intersection, not a translation.
create table if not exists public.catalog_products (
  id                 bigint generated by default as identity primary key,
  org_id             bigint not null references public.orgs(id),
  template_id        bigint not null references public.product_templates(id),
  template_revision  int not null,
  name               text not null,
  sku                text,
  description        text,
  status             text not null default 'draft' check (status in ('draft','active','archived')),
  field_policies     jsonb not null default '{}'::jsonb,
  image_url          text,
  sort_order         int not null default 0,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);
create index if not exists catalog_products_org_idx on public.catalog_products(org_id, status);

-- ============================================================
-- L3 — commerce data
-- ============================================================

-- Fabric/option price groups: the level price grids attach to (anchor customer's RSA..RSD,
-- WWA..WWE, Group1..7 all become rows here).
create table if not exists public.price_groups (
  id          bigint generated by default as identity primary key,
  org_id      bigint not null references public.orgs(id),
  key         text not null,
  label       text,
  created_at  timestamptz not null default now(),
  unique (org_id, key)
);

-- Which option value routes to which price group, per product: e.g. (fabricColor,'cream') → RSA.
-- Image/pattern options can alternatively carry priceGroup directly in the policy's
-- allowedPatterns entries; this table is the general mapping for select/color values.
create table if not exists public.price_group_maps (
  id              bigint generated by default as identity primary key,
  org_id          bigint not null references public.orgs(id),
  product_id      bigint not null references public.catalog_products(id) on delete cascade,
  field_key       text not null,
  value_token     text not null,
  price_group_id  bigint not null references public.price_groups(id),
  unique (product_id, field_key, value_token)
);

-- W×H MSRP step matrices. Lookup rounds UP to the next break on both axes (the anchor
-- customer's Excel MATCH(...,-1) semantics). cells is rows-by-height × cols-by-width, JSON
-- number or null; null = size not manufacturable (their grids encode feasibility as N/A).
create table if not exists public.price_grids (
  id              bigint generated by default as identity primary key,
  org_id          bigint not null references public.orgs(id),
  price_group_id  bigint not null references public.price_groups(id) on delete cascade,
  currency        text not null default 'USD',
  width_breaks    numeric[] not null,   -- ascending, inches
  height_breaks   numeric[] not null,   -- ascending, inches
  cells           jsonb not null,       -- number|null [heightIdx][widthIdx]
  effective_from  timestamptz not null default now(),
  effective_to    timestamptz,
  note            text,
  changed_by      text,
  created_at      timestamptz not null default now()
);
create index if not exists price_grids_group_idx on public.price_grids(price_group_id, effective_from);

-- Option surcharges. matcher: {fieldKey, valueToken} or {fieldKey, anyOf:[tokens]} or
-- {fieldKey} (any non-default value). kind decides how amount is read:
--   flat          {value}                       — e.g. hub $185
--   per_unit      {value}                       — per qty
--   percent       {pct}                         — e.g. hidden gear +15%
--   width_band    {breaks:[...in], values:[...]} — e.g. cordless $135..$250 by width
--   per_linear_ft {value, dimension:'height'|'width'} — e.g. side channel $/ft
create table if not exists public.surcharge_rules (
  id              bigint generated by default as identity primary key,
  org_id          bigint not null references public.orgs(id),
  product_id      bigint references public.catalog_products(id) on delete cascade,  -- NULL = org-wide
  label           text not null,
  matcher         jsonb not null,
  kind            text not null check (kind in ('flat','per_unit','percent','width_band','per_linear_ft')),
  amount          jsonb not null,
  effective_from  timestamptz not null default now(),
  effective_to    timestamptz,
  created_at      timestamptz not null default now()
);
create index if not exists surcharge_rules_org_idx on public.surcharge_rules(org_id, product_id);

-- Size limits per option value: the (optionValue, dimension, min, max) tuples the customer's
-- SIZE LIMITATION sheets already tabulate. dimension 'area_sqft' covers rules like
-- "over 64 sqft not available with this option". message is shown inline in the configurator.
create table if not exists public.size_constraints (
  id          bigint generated by default as identity primary key,
  org_id      bigint not null references public.orgs(id),
  product_id  bigint references public.catalog_products(id) on delete cascade,      -- NULL = org-wide
  matcher     jsonb not null,
  dimension   text not null check (dimension in ('width','height','area_sqft')),
  min_value   numeric,
  max_value   numeric,
  message     text,
  created_at  timestamptz not null default now()
);
create index if not exists size_constraints_org_idx on public.size_constraints(org_id, product_id);

-- Dealer price = MSRP total × factor. Factor resolves most-specific-first:
-- (dealer, product) → (dealer, line_key) → (dealer, NULL both) → error (no implicit 1.0 —
-- an unpriced dealer must be caught loudly, not silently sold at MSRP).
create table if not exists public.account_factors (
  id                 bigint generated by default as identity primary key,
  org_id             bigint not null references public.orgs(id),
  dealer_account_id  bigint not null references public.dealer_accounts(id) on delete cascade,
  product_id         bigint references public.catalog_products(id) on delete cascade,
  line_key           text,
  factor             numeric not null check (factor > 0),
  effective_from     timestamptz not null default now(),
  effective_to       timestamptz,
  created_at         timestamptz not null default now()
);
create index if not exists account_factors_dealer_idx on public.account_factors(dealer_account_id);

-- Freight rules, e.g. UPS Ground $7/unit jumping to $95/unit over 93.875" width; Will Call $0.
-- matcher: {} (always) or {dimension:'width', gt: 93.875}. amount: {perUnit} v1.
create table if not exists public.freight_rules (
  id          bigint generated by default as identity primary key,
  org_id      bigint not null references public.orgs(id),
  method      text not null,
  label       text,
  matcher     jsonb not null default '{}'::jsonb,
  amount      jsonb not null,
  sort_order  int not null default 0,
  created_at  timestamptz not null default now()
);

-- ============================================================
-- RLS
-- ============================================================
-- Same posture as the accessory catalog: catalog/pricing data is readable by any signed-in user
-- (v1 single org; org scoping enforced in app queries), writable by admins only. The app's
-- service-role reads bypass RLS as elsewhere. Dealer users may read their own dealer account;
-- factors are admin-read via service role only (dealers see net prices, never their factor).

do $$
declare t text;
begin
  foreach t in array array[
    'orgs','dealer_accounts','product_templates','catalog_products','price_groups',
    'price_group_maps','price_grids','surcharge_rules','size_constraints',
    'account_factors','freight_rules'
  ] loop
    execute format('alter table public.%I enable row level security', t);
  end loop;
end $$;

-- Readable catalog surface for signed-in users.
do $$
declare t text;
begin
  foreach t in array array['orgs','product_templates','catalog_products','price_groups','freight_rules'] loop
    execute format('drop policy if exists %I_read on public.%I', t, t);
    execute format('create policy %I_read on public.%I for select using (auth.role() = ''authenticated'')', t, t);
  end loop;
end $$;

-- Pricing internals: admin-only via RLS (app reads for pricing go through service role).
do $$
declare t text;
begin
  foreach t in array array['price_group_maps','price_grids','surcharge_rules','size_constraints','account_factors'] loop
    execute format('drop policy if exists %I_admin_read on public.%I', t, t);
    execute format('create policy %I_admin_read on public.%I for select using (public.is_admin())', t, t);
  end loop;
end $$;

-- Dealer users can read their own dealer account row.
drop policy if exists dealer_accounts_own_read on public.dealer_accounts;
create policy dealer_accounts_own_read on public.dealer_accounts for select using (
  public.is_admin()
  or id = (select dealer_account_id from public.profiles where id = auth.uid())
);

-- All writes: admin only.
do $$
declare t text;
begin
  foreach t in array array[
    'orgs','dealer_accounts','product_templates','catalog_products','price_groups',
    'price_group_maps','price_grids','surcharge_rules','size_constraints',
    'account_factors','freight_rules'
  ] loop
    execute format('drop policy if exists %I_admin_write on public.%I', t, t);
    execute format('create policy %I_admin_write on public.%I for all using (public.is_admin()) with check (public.is_admin())', t, t);
  end loop;
end $$;
