-- Window ERP Phase B (first slice): manufacturing deduction tables.
--
-- The anchor factory's MO workbooks derive every cut length from the ordered size via a
-- (mount × assembly-type) → per-component signed-offset matrix ("Deductions" sheets). Their
-- changelog shows these offsets are re-tuned monthly from production feedback, so they are
-- versioned org data, never code.
--
-- matcher: ARRAY of RuleMatcher ({fieldKey, valueToken|anyOf|truthy}) — ALL must match the
-- line's effective selections. Rows are tried in sort_order; first match wins per component
-- set. components: { componentKey: { offset: inches, base: 'width'|'height', label } } —
-- cut = base dimension + offset (e.g. tube: width − 1.25; fabricLength: height + 12).
create table if not exists public.deduction_tables (
  id              bigint generated by default as identity primary key,
  org_id          bigint not null references public.orgs(id),
  line_key        text not null,                 -- product line this row applies to
  label           text not null,                 -- human name, e.g. "Cassette · Inside Mount"
  matcher         jsonb not null default '[]'::jsonb,
  components      jsonb not null default '{}'::jsonb,
  sort_order      int not null default 0,
  effective_from  timestamptz not null default now(),
  effective_to    timestamptz,
  note            text,
  created_at      timestamptz not null default now()
);
create index if not exists deduction_tables_org_idx on public.deduction_tables(org_id, line_key);

alter table public.deduction_tables enable row level security;
drop policy if exists deduction_tables_admin_read on public.deduction_tables;
create policy deduction_tables_admin_read on public.deduction_tables for select using (public.is_admin());
drop policy if exists deduction_tables_admin_write on public.deduction_tables;
create policy deduction_tables_admin_write on public.deduction_tables for all using (public.is_admin()) with check (public.is_admin());
