-- Window ERP Phase C (first slice): retail CRM — leads + measure/install appointments.
-- Modeled on the anchor customer's MF (measure form) workbook: a sales funnel with follow-up
-- dates, referral source, site-access details, and measure→install scheduling. Own tables,
-- own blade; nothing here touches the live quoting surfaces.

create table if not exists public.window_leads (
  id              bigint generated by default as identity primary key,
  org_id          bigint not null references public.orgs(id),
  name            text not null,
  phone           text,
  email           text,
  address         text,
  city            text,
  state           text,
  zip             text,
  -- Where the lead came from (referral, website, walk-in, ...) and who's on it.
  source          text,
  assignee        text,
  status          text not null default 'new'
                  check (status in ('new','contacted','measure_scheduled','quoted','won','lost')),
  -- The MF sheet's operational fields: gate codes, preferred language, competitor...
  details         jsonb not null default '{}'::jsonb,
  notes           text,
  next_follow_up  date,
  quote_id        bigint references public.quotes(id),   -- linked once a quote exists
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);
create index if not exists window_leads_org_idx on public.window_leads(org_id, status);

create table if not exists public.window_appointments (
  id            bigint generated by default as identity primary key,
  org_id        bigint not null references public.orgs(id),
  lead_id       bigint not null references public.window_leads(id) on delete cascade,
  kind          text not null default 'measure' check (kind in ('measure','install','repair')),
  scheduled_at  timestamptz not null,
  duration_min  int not null default 60,
  assignee      text,
  status        text not null default 'scheduled' check (status in ('scheduled','completed','cancelled')),
  notes         text,
  created_at    timestamptz not null default now()
);
create index if not exists window_appointments_org_idx on public.window_appointments(org_id, scheduled_at);

-- RLS: back-office data, admin only (same posture as pricing internals).
alter table public.window_leads enable row level security;
alter table public.window_appointments enable row level security;
do $$
declare t text;
begin
  foreach t in array array['window_leads','window_appointments'] loop
    execute format('drop policy if exists %I_admin_all on public.%I', t, t);
    execute format('create policy %I_admin_all on public.%I for all using (public.is_admin()) with check (public.is_admin())', t, t);
  end loop;
end $$;
